name: Deploy AWS Infra

on:
  push:
    branches:
      - main  #current main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ensure latest commit history is pulled

      - name: Debug - List Repo Files Before Terraform
        run: ls -R aws_config/dev  # check if dev.tf present

      - name: Wait for Files
        run: sleep 5  # short delay to ensure files are fully available

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest  # install latest terraform

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # hard coded for now (can be configured)

      - name: Initialize Terraform
        run: terraform init
        working-directory: aws_config/dev  # terraform path

      - name: Debug - List Repo Files After Terraform Init
        run: ls -R aws_config/dev  # terraform files

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: aws_config/dev  # terraform path

      - name: Debug - Terraform Apply Completion
        run: echo "Terraform apply completed successfully."
